spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  datasource:
    hikari:
      connection-timeout: '60000'
      pool-name: testHikariPool
      idle-timeout: '60000'
      maximum-pool-size: '10'
      max-lifetime: '30000'
      minimum-idle: '5'
    password: ''
    username: root
    url: jdbc:mysql://localhost:3306/concretepage?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
  application:
    name: request-payload-validation
server:
  port: '8384'
